Vagrant.configure("2") do |config|
    
  config.vm.define "n1" do |n1|
    n1.vm.box = "ubuntu/focal64"
    n1.vm.hostname = "n1"
    n1.vm.network "private_network", ip: "172.24.1.10"
    n1.disksize.size = "120GB"

    n1.vm.provider "virtualbox" do |vb|
      vb.name = "n1"
      vb.gui = false
      vb.memory = 32768
      vb.cpus = 8
      vb.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
      # Enable nested paging for memory management in hardware
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      # Use large pages to reduce Translation Lookaside Buffers usage
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      # Use virtual processor identifiers  to accelerate context switching
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    n1.vm.disk :disk, name: "sdb", size: "120GB"
    n1.vm.disk :disk, name: "sdc", size: "120GB"
    n1.vm.disk :disk, name: "sdb", size: "120GB"
    n1.vm.provision :shell, path: "provision.sh"
  end

  config.vm.define "n2" do |n2|
    n2.vm.box = "ubuntu/focal64"
    n2.vm.hostname = "n2"
    n2.vm.network "private_network", ip: "172.24.1.11"
    n2.disksize.size = "120GB"

    n2.vm.provider "virtualbox" do |vb|
      vb.name = "n2"
      vb.gui = false
      vb.memory = 32768
      vb.cpus = 8
      vb.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
      # Enable nested paging for memory management in hardware
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      # Use large pages to reduce Translation Lookaside Buffers usage
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      # Use virtual processor identifiers  to accelerate context switching
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    n2.vm.disk :disk, name: "sdb", size: "120GB"
    n2.vm.disk :disk, name: "sdc", size: "120GB"
    n2.vm.disk :disk, name: "sdb", size: "120GB"
    n2.vm.provision :shell, path: "provision.sh"
  end

  config.vm.define "n3" do |n3|
    n3.vm.box = "ubuntu/focal64"
    n3.vm.hostname = "n3"
    n3.vm.network "private_network", ip: "172.24.1.12"
    n3.disksize.size = "120GB"

    n3.vm.provider "virtualbox" do |vb|
      vb.name = "n3"
      vb.gui = false
      vb.memory = 32768
      vb.cpus = 8
      vb.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
      # Enable nested paging for memory management in hardware
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      # Use large pages to reduce Translation Lookaside Buffers usage
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      # Use virtual processor identifiers  to accelerate context switching
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]      
    end

    n3.vm.disk :disk, name: "sdb", size: "120GB"
    n3.vm.disk :disk, name: "sdc", size: "120GB"
    n3.vm.disk :disk, name: "sdb", size: "120GB"
    n3.vm.provision :shell, path: "provision.sh"
  end
    
  config.vm.define "n4" do |n4|
    n4.vm.box = "ubuntu/focal64"
    n4.vm.hostname = "n4"
    n4.vm.network "private_network", ip: "172.24.1.13"
    n4.disksize.size = "120GB"

    n4.vm.provider "virtualbox" do |vb|
      vb.name = "n4"
      vb.gui = false
      vb.memory = 32768
      vb.cpus = 8
      vb.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
      # Enable nested paging for memory management in hardware
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      # Use large pages to reduce Translation Lookaside Buffers usage
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      # Use virtual processor identifiers  to accelerate context switching
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]      
    end

    n4.vm.disk :disk, name: "sdb", size: "120GB"
    n4.vm.disk :disk, name: "sdc", size: "120GB"
    n4.vm.disk :disk, name: "sdb", size: "120GB"
    n4.vm.provision :shell, path: "provision.sh"
  end
    
  config.vm.define "n5" do |n5|
    n5.vm.box = "ubuntu/focal64"
    n5.vm.hostname = "n5"
    n5.vm.network "private_network", ip: "172.24.1.14"
    n5.disksize.size = "120GB"

    n5.vm.provider "virtualbox" do |vb|
      vb.name = "n5"
      vb.gui = false
      vb.memory = 32768
      vb.cpus = 8
      vb.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
      # Enable nested paging for memory management in hardware
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      # Use large pages to reduce Translation Lookaside Buffers usage
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      # Use virtual processor identifiers  to accelerate context switching
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]      
    end

    n5.vm.disk :disk, name: "sdb", size: "120GB"
    n5.vm.disk :disk, name: "sdc", size: "120GB"
    n5.vm.disk :disk, name: "sdb", size: "120GB"
    n5.vm.provision :shell, path: "provision.sh"
  end

  config.vm.define "n6" do |n6|
    n6.vm.box = "ubuntu/focal64"
    n6.vm.hostname = "n6"
    n6.vm.network "private_network", ip: "172.24.1.15"
    n6.disksize.size = "120GB"

    n6.vm.provider "virtualbox" do |vb|
      vb.name = "n6"
      vb.gui = false
      vb.memory = 32768
      vb.cpus = 8
      vb.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
      # Enable nested paging for memory management in hardware
      vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
      # Use large pages to reduce Translation Lookaside Buffers usage
      vb.customize ["modifyvm", :id, "--largepages", "on"]
      # Use virtual processor identifiers  to accelerate context switching
      vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]      
    end

    n6.vm.disk :disk, name: "sdb", size: "120GB"
    n6.vm.disk :disk, name: "sdc", size: "120GB"
    n6.vm.disk :disk, name: "sdb", size: "120GB"
    n6.vm.provision :shell, path: "provision.sh"
  end
end
