Vagrant.configure("2") do |config|
  config.vm.define "n1" do |n1|
    n1.vm.box = "ubuntu/xenial64"
    n1.vm.hostname = "n1"
    n1.vm.network "private_network", ip: "172.24.1.10"

    n1.vm.provider "virtualbox" do |vb|
      vb.name = "n1"
      vb.gui = false
      vb.memory = 24768
      vb.cpus = 8
    end

    n1.vm.provision :shell, path: "provision.sh"
  end

  config.vm.define "n2" do |n2|
    n2.vm.box = "ubuntu/xenial64"
    n2.vm.hostname = "n2"
    n2.vm.network "private_network", ip: "172.24.1.11"

    n2.vm.provider "virtualbox" do |vb|
      vb.name = "n2"
      vb.gui = false
      vb.memory = 8072
      vb.cpus = 4
    end

    n2.vm.provision :shell, path: "provision.sh"
  end

  config.vm.define "n3" do |n3|
    n3.vm.box = "ubuntu/xenial64"
    n3.vm.hostname = "n3"
    n3.vm.network "private_network", ip: "172.24.1.12"

    n3.vm.provider "virtualbox" do |vb|
      vb.name = "n3"
      vb.gui = false
      vb.memory = 8072
      vb.cpus = 4
    end

    n3.vm.provision :shell, path: "provision.sh"
  end
end
